services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d