spring:
    config:
        activate:
            on-profile: local
    datasource:
        url: jdbc:postgresql://localhost:5432/todo_db
        username: postgres
        password: example
        driver-class-name: org.postgresql.Driver
logging:
    level:
        org.springframework.boot.web: INFO