### Add new to list
POST http://localhost:8080/todos
Content-Type: application/json

{
  "title": "Message 1",
  "description": "Message 1 description"
}

### Add nr 2 to list
POST http://localhost:8080/todos
Content-Type: application/json

{
  "title": "Message 2",
  "description": "Message 2 description"
}


### Get all the messages
GET http://localhost:8080/todos

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}



### Find by id
GET http://localhost:8080/todos/c02c31e8-49c4-4d7f-8d1a-43e38acde273

### Find by id, but fail
GET http://localhost:8080/todos/c02c31e8-49c4-4d7f-8d1a-43e38acde274

### Delete by
DELETE http://localhost:8080/todos/c02c31e8-49c4-4d7f-8d1a-43e38acde273

### Mark as complete
PATCH http://localhost:8080/todos/markcomplete/c02c31e8-49c4-4d7f-8d1a-43e38acde273