### Add new to list
POST http://localhost:8080/todos
Content-Type: application/json

{
  "title": "Message 1",
  "description": "Message 1 description"
}

### Add nr 2 to list
POST http://localhost:8080/todos
Content-Type: application/json

{
  "title": "Message 2",
  "description": "Message 2 description"
}


### Get all the messages
GET http://localhost:8080/todos

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}



### Find by id
GET http://localhost:8080/todos/5927204e-be22-42c1-ae3c-d36675454c2d


### Delete by
DELETE http://localhost:8080/todos/5927204e-be22-42c1-ae3c-d36675454c2d

### Mark as complete
PATCH http://localhost:8080/todos/markcomplete/5927204e-be22-42c1-ae3c-d36675454c2d