### Add new to list
POST http://localhost:8080/new
Content-Type: application/json

{
  "title": "Message 1",
  "description": "Message 1 description"
}

### Add nr 2 to list
POST http://localhost:8080/new
Content-Type: application/json

{
  "title": "Message 2",
  "description": "Message 2 description"
}



### Get all the messages
GET http://localhost:8080/

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}



### Find by id
GET http://localhost:8080/find?id=883e3d13-5934-4cf8-8cf6-c280a13866a8
Accept: application/json

### Delete by
POST http://localhost:8080/delete?id=883e3d13-5934-4cf8-8cf6-c280a13866a8

### Mark as complete
POST http://localhost:8080/markfinished?id=883e3d13-5934-4cf8-8cf6-c280a13866a8